name: memory_lane

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  google_sign_in: ^6.1.4

  # State Management
  provider: ^6.1.4

  # Location Services
  google_maps_flutter: ^2.12.0
  location: ^8.0.0
  geolocator: ^13.0.3

  # UI Elements
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1

  # Media Utils
  image_picker: ^1.1.2
  video_player: ^2.9.5

  # Storage
  shared_preferences: ^2.5.3

  # Utils
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0

  # Icons
  cupertino_icons: ^1.0.8

  # New dependencies
  geocoding: ^2.2.0
  http: ^1.2.1

  # Added from the code block
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env


  # Uncomment and add fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
